from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import DateTime, ForeignKey, Numeric, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from apps.api.db.base import Base

# "draft": generated but the period isn't locked yet (can still change).
# "final": the period is locked — immutable from here on, corrections are
# UsageAdjustment rows against a later period. "void": manually cancelled by
# a platform admin (e.g. issued in error).
INVOICE_STATUSES = ("draft", "final", "void")


class Invoice(Base):
    """One org's billing summary for one period, generated by
    workers/billing_worker.py at period close (req §16). This is a Veerox-
    generated *summary/estimate* document, not a payment instrument — no
    payment gateway is involved (see docs/razorpay-billing-removal.md); an
    org's actual license/payment stays a manually-managed, off-platform
    process via routers/billing.py's license endpoints.
    """

    __tablename__ = "invoices"
    __table_args__ = (
        UniqueConstraint("org_id", "billing_period", name="uq_invoices_org_period"),
    )

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    org_id: Mapped[UUID] = mapped_column(ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False)
    billing_period: Mapped[str] = mapped_column(String(7), nullable=False)
    usage_charge: Mapped[Decimal] = mapped_column(
        Numeric(14, 4), nullable=False, server_default="0"
    )
    platform_fee: Mapped[Decimal] = mapped_column(
        Numeric(14, 4), nullable=False, server_default="0"
    )
    total_amount: Mapped[Decimal] = mapped_column(
        Numeric(14, 4), nullable=False, server_default="0"
    )
    currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default="USD")
    status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="draft")
    locked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
